version: "3.9"

services:
  frontend-builder:
    build: ./frontend
    image: ghcr.io/pavel-savelev/film-frontend:latest
    volumes:
      - frontend_dist:/app/dist
    networks:
      - app-network
  backend:
    build: ./backend
    image: ghcr.io/pavel-savelev/film-backend:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build: ./nginx
    image: ghcr.io/pavel-savelev/film-nginx:latest
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app-network

volumes:
  frontend_dist:
  pgdata:
  pgadmindata:

networks:
  app-network:
    driver: bridge
