version: "3.9"

services:
  frontend-builder:
    build: ./frontend
    image: ghcr.io/pavel-savelev/film-frontend:latest
    volumes:
      - frontend_dist:/app/dist
    networks:
      - app-network
    restart: unless-stopped
  backend:
    build: ./backend
    image: ghcr.io/pavel-savelev/film-backend:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_DRIVER=${DATABASE_DRIVER}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    build: ./nginx
    image: ghcr.io/pavel-savelev/film-nginx:latest
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER=${POSTGRES_USER}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  frontend_dist:
  pgdata:
  pgadmindata:

networks:
  app-network:
    driver: bridge

