server {
    listen 80;

    # Раздача фронтенда
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # Проксирование API запросов на backend
    location /api/ {
        proxy_pass http://backend:3000/;
    }

    location /content/ {
        proxy_pass http://backend:3000/content/;
    }
}